services:

    links.softwareshinobi.come:

        container_name: links.softwareshinobi.com

        image: softwareshinobi/links.softwareshinobi.com

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - 8000:80
